# Generated by Django 5.2.17 on 2026-09-06 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Alamat Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Nomor Telepon/HP')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit / Debit Card'), ('gopay', 'GoPay')], max_length=30, verbose_name='Metode Pembayaran')),
                ('midtrans_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Midtrans Subscription ID')),
                ('midtrans_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Midtrans Token (Saved Card Token / GoPay Token)')),
                ('gopay_account_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='GoPay Account ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status Langganan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Testing Plan - Monthly', max_length=255, verbose_name='Nama Paket')),
                ('amount', models.IntegerField(default=10000, verbose_name='Harga (IDR)')),
                ('interval', models.IntegerField(default=1, verbose_name='Interval')),
                ('interval_unit', models.CharField(choices=[('day', 'Hari'), ('week', 'Minggu'), ('month', 'Bulan')], default='month', max_length=20, verbose_name='Satuan Interval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='Order ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('payment_type', models.CharField(max_length=50, verbose_name='Payment Type')),
                ('gross_amount', models.CharField(max_length=50, verbose_name='Gross Amount')),
                ('transaction_status', models.CharField(max_length=50, verbose_name='Transaction Status')),
                ('is_recurring_charge', models.BooleanField(default=False, verbose_name='Recurring Charge Otomatis?')),
                ('raw_notification', models.JSONField(blank=True, default=dict, verbose_name='Raw Notification Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Transaksi')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionlog_set', to='payments.subscriber', verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
